Fix NoSuchMethodError when using GEF 3.19 or higher
The method getDrawerFigure() has been removed and getFigure() should be
used instead. On older GEF releases, this method returns a plain
IFigure, so to ensure backwards compatibility, one needs to do an
explicit cast.

Fixes https://github.com/eclipse/org.eclipse.rcptt/issues/79