Fix preference listener removal
java.lang.IllegalStateException: Preference node
"org.eclipse.e4.ui.workbench.renderers.swt" has been removed.
	at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:170)
	at org.eclipse.core.internal.preferences.EclipsePreferences.removePreferenceChangeListener(EclipsePreferences.java:960)
	at org.eclipse.e4.ui.workbench.renderers.swt.CTabRendering.lambda$0(CTabRendering.java:177)